### ISSUE TITLE
Cuda Version

### ISSUE THREAD

**Issue by 106AbdulBasit** [AI4Bharat/IndicTrans2#14]
Hi team,
Steps that I have taken all the steps which is listed in readme in order to run the inference 

I have downloaded the model checkpoints and  I try to run the inference using the Python code

```
from inference.engine import Model
model = Model('indic-en-preprint/ct2_int8_model/', model_type="ctranslate2")
```

This gives me the error, the error is below

"RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version"

My Cuda version is 

11.8

Error number 2

If I try to run the fairseq inference the kernel becomes dead.

Can you guide me on how to resolve this issue, I will be very thankful to you.

Kind Regards
Abdul Basit

**Comment by PranjalChitale** [comment]
1. Please check the version number of your NVIDIA driver and ascertain whether it supports CUDA 11.8.
2. Please check if the system CUDA version matches the PyTorch CUDA version.

You can refer to the following page, this will help you resolve the issue.

https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers

Once this issue is resolved, both fairseq inference as well as Python inference will work as expected.
